[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off

[INPUT]
    Name         tail
    Path         /tmp/app.log
    Tag          app.logs

[FILTER]
    Name         record_modifier
    Match        *
    Record       job fluent-bit
    Record       env development
    Record       app poc-app

[OUTPUT]
    Name         loki
    Match        *
    # Loki address in AWS (e.g. Load Balancer in front of EKS)
    Host         ${LOKI_HOST}
    Port         443
    TLS          On
    # For PoC without authentication, in production recommended via Basic Auth or VPC endpoint
    # http_user   admin
    # http_passwd password
    Labels       job=fluent-bit, env=development, app=poc-app
    Line_Format  json
    LogLevel     info
